version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-195-143-54.compute-1.amazonaws.com
            port: '5432'
            database: d1ju10vkemeqlm
            ssl: true
            user: owfqvxhofrhbcd
            password: 9b3b6053e1e030e7a9e25389314ba9af717965da3d6a77fe82fee71aced962f2
            migrations: true